### ISSUE TITLE
Check PID with trajectory issues

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/paper-ephys-atlas#16]
Launching this code:
ibldevtools/Gaelle/gc-ephys-atlas/scratch_169__plot_all_insertions.py

These PIDs are problematic:
ERROR - fdeff6df-7216-4b83-ab64-241e9fd173da
ERROR - 8f2e16c4-893b-4f8f-bfb2-94fa452710ec
ERROR - 2b5ebb3e-273c-400d-bf35-33e87cbe46fb
ERROR - 9861fa24-d998-4ef5-9606-89002b8706fc
ERROR - b72b22c2-6e9d-4604-9910-20c0e1a467d7

**Comment by GaelleChapuis** [comment]
fdeff6df-7216-4b83-ab64-241e9fd173da
ValueError: At least one z value lies outside of the atlas volume.

**Comment by GaelleChapuis** [comment]
![Image](https://github.com/user-attachments/assets/8a6525c4-e2c3-44cd-b587-1cd6723ffe99)

**Comment by GaelleChapuis** [comment]
2b5ebb3e-273c-400d-bf35-33e87cbe46fb

No plot

`ephysalign = EphysAlignment(xyz_picks, depths)`
ValueError: At least one z value lies outside of the atlas volume.

**Comment by GaelleChapuis** [comment]
![Image](https://github.com/user-attachments/assets/37e1edc6-7215-486b-b960-5d3f18da380e)

**Comment by GaelleChapuis** [comment]
![Image](https://github.com/user-attachments/assets/edad6c07-c086-4fb5-83db-9183d98477b7)
